# 通用配置
# 与特定环境相关的配置放在application-default.xml，通过maven profile覆盖
spring:
  application:
    admin:
      enabled: true
    name: cornel_website
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
      default-property-inclusion: non_null

#  profiles:
#    active:
#      - dev
  aop:
    proxy-target-class: true
  datasource:
    initialization-mode: never
  mvc:
    log-resolved-exception: true
    pathmatch:
      use-suffix-pattern: true
      use-registered-suffix-pattern: true
    contentnegotiation:
      favor-path-extension: true
      parameter-name: format
  sleuth:
    sampler:
      probability: 1
    enabled: true
    annotation:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
http:
  maxIdle: 5
  keepAlive: 3
  connectTimeout: 20
  readTimeout: 120
  writeTimeout: 60

kafka:
  tracing:
    enabled: false

mybatis:
  config-location: 'classpath:mybatis-config.xml'
  mapper-locations: 'classpath:mapper/*.xml'

xxl:
 job:
  admin:
   addresses: http://182.92.1.233:9528
  accessToken: ''
  executor:
   appname: cornel
   ip: 182.92.1.233
   port: 9999
   logpath: '/home/www/cornel_web/logs/'
   logretentiondays: 10



