debug: true

#redis 集群模式
spring:
  redis:
    cluster:
      nodes: 150.242.184.16:6380,150.242.184.16:6381,150.242.184.16:6382
      max-redirects: 5
      password: cornel00147258
      timeout: 5

jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    default:
      type: caffeine
      limit: 100
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      expireAfterWriteInMillis: 60000
# remote 需要适配下公司sedis或者redis集群
#  remote:
#    default:
#      type: redis.lettuce
#      keyConvertor: fastjson
#      valueEncoder: java
#      valueDecoder: java
#      uri:
#        - redis://l-schrd2.vc.beta.cn0:6379
#        - redis://l-schrd2.vc.beta.cn0:7379
#      password:
#        - schrd

caching:
  types:
    - CAFFEINE
  config:
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1h,recordStats
  configs:
    hblist:
      caffeine:
        spec: maximumSize=5000,expireAfterAccess=10s,recordStats
    flist:
      caffeine:
        spec: maximumSize=5000,expireAfterAccess=15m,refreshAfterWrite=10m,recordStats
      redis:
        timeToLive: 15m

we-chat:
   code2session: https://api.weixin.qq.com/sns/jscode2session?appid={appId}&secret={appSecret}&js_code={jscode}&grant_type=authorization_code
   appId: wx5bde5e1ca69bd7f6
   appSecret: 80dc07ef341d0c59314d935378075068

ali-config:
    accessKeyId: LTAI4FjjDZfU5McHXiDEH2Uk
    accessSecret: 1C6KdK5kBZurVkFTSqp8wPE2mvJpBB
    loginValidcodeId: SMS_176539582
    priceChangeCodeId: SMS_205821111
    notifyBusinessOp: SMS_205826428
    notifyFinanceOp: SMS_205811656
        
datasources:
  dm-master:
    driverClassName: org.postgresql.Driver
    jdbcUrl: 'jdbc:postgresql://192.168.0.107:5432/cornel_beta'
    username: cornel_prd
    password: a9e43160-7d34-4a9d-8120-f605b111ce59
    maximumPoolSize: 5
    idleTimeout: 600000
    maxLifetime: 1800000
baidu:
  ak: 1EBYcarYLWPnnpUbrX4SUxQwtLSjgvF0
service:
  mobile: 18904015597,18904015597
